---
apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
  name: simple-hdfs
spec:
  image:
    productVersion: 3.4.1
  clusterConfig:
    zookeeperConfigMapName: simple-hdfs-znode
    dfsReplication: 1
    authentication: null
  nameNodes:
    config:
      listenerClass: external-stable
      resources:
        memory:
          limit: 512Mi
        cpu:
          max: "0.5"
    roleGroups:
      default:
        replicas: 2
  dataNodes:
    config:
      listenerClass: external-unstable
      resources:
        memory:
          limit: 512Mi
        cpu:
          max: "0.5"
    roleGroups:
      default:
        replicas: 1
  journalNodes:
    config:
      resources:
        memory:
          limit: 256Mi
        cpu:
          max: "0.25"
    roleGroups:
      default:
        replicas: 1