---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple-kafka
spec:
  image:
    productVersion: 3.9.1
  clusterConfig:
    tls:
      serverSecretClass: tls  # Use Stackable's default TLS
      internalSecretClass: tls
    zookeeperConfigMapName: simple-kafka-znode
  brokers:
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            memory:
              limit: 2Gi
            cpu:
              max: "1"
        configOverrides:
          server.properties:
            # Retention: 7 days (168 hours) for Kappa architecture replayability
            log.retention.hours: "168"
            # Segment size: 100MB for efficient log compaction
            log.segment.bytes: "104857600"
            # Retention check interval: every 5 minutes
            log.retention.check.interval.ms: "300000"