---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple-kafka
spec:
  image:
    productVersion: 3.9.1
  clusterConfig:
    tls:
      serverSecretClass: null
    zookeeperConfigMapName: simple-kafka-znode
  brokers:
    config:
      bootstrapListenerClass: external-unstable # Stacklet exposure outside of k8s. Remove if not needed.
      brokerListenerClass: external-unstable # Stacklet exposure outside of k8s. Remove if not needed.
      default:
        replicas: 1 # 3 is recommended for production, 1 for testing