apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-producer-script
data:
  feed_data.py: |
    import csv
    import json
    import glob
    import os
    import time
    from kafka import KafkaProducer

    # Use internal K8s address
    bootstrap = os.environ.get("KAFKA_BOOTSTRAP_SERVERS", "simple-kafka-broker-default-bootstrap.default.svc.cluster.local:9092")

    print(f"--- Connecting to Kafka at {bootstrap} ---")
    # Retry logic in case Broker is slow to wake up
    for i in range(5):
        try:
            producer = KafkaProducer(
                bootstrap_servers=[bootstrap],
                value_serializer=lambda x: json.dumps(x).encode('utf-8')
            )
            print("Connected successfully.")
            break
        except Exception as e:
            print(f"Connection failed (attempt {i+1}/5): {e}")
            time.sleep(2)

    def send_csv(file, topic):
        try:
            print(f"Processing file: {file} -> Topic: {topic}")
            with open(file, 'r', encoding='utf-8') as f:
                reader = csv.DictReader(f)
                count = 0
                for row in reader:
                    # Basic Type Conversion
                    if "votes_up" in row:
                        try:
                             row["votes_up"] = int(row["votes_up"])
                             row["review_id"] = int(row["review_id"])
                             row["weighted_vote_score"] = float(row["weighted_vote_score"])
                             row["recommended"] = str(row["recommended"]).lower() == "true"
                             row["steam_purchase"] = str(row["steam_purchase"]).lower() == "true"
                        except ValueError: continue
                    if "player_count" in row:
                        try:
                            row["player_count"] = int(row["player_count"])
                            row["appid"] = int(row["appid"])
                        except ValueError: continue
                    
                    producer.send(topic, value=row)
                    count += 1
            print(f"Successfully sent {count} records from {file}")
        except Exception as e:
            print(f"Error reading {file}: {e}")

    # Process reviews
    files = glob.glob('/inputs/reviews/*.csv')
    if not files: print("WARNING: No review files found!")
    for f in files: send_csv(f, 'steam-reviews')

    # Process charts
    files = glob.glob('/inputs/charts/*.csv')
    if not files: print("WARNING: No chart files found!")
    for f in files: send_csv(f, 'steam-charts')

    producer.flush()
    print("All Data Pushed to Kafka.")