apiVersion: v1
kind: Pod
metadata:
  name: producer-runner
spec:
  containers:
    - name: python-producer
      image: python:3.9
      command: ["/bin/sh", "-c", "pip install kafka-python && sleep 3600"]
      env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "simple-kafka-broker-default-bootstrap.default.svc.cluster.local:9092"
      volumeMounts:
        - name: script-volume
          mountPath: /app
  volumes:
    - name: script-volume
      configMap:
        name: kafka-producer-script