apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: kafka-test-output
  namespace: default
spec:
  sparkImage:
    productVersion: "3.5.6"
    pullPolicy: "IfNotPresent"
  mode: cluster
  mainApplicationFile: "local:///opt/spark/work-dir/pyspark_kafka_print_schema.py"

  deps:
    packages:
      - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.6
    requirements:
      - kafka-python==2.0.2

  sparkConf:
    spark.app.name: "KafkaTestOutput"
    spark.hadoop.fs.defaultFS: "hdfs://simple-hdfs-namenode-default-0.simple-hdfs-namenode-default.default.svc.cluster.local:8020"
    spark.driver.memory: 512m
    spark.executor.memory: 512m

  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: "simple-kafka-broker-default-bootstrap.default.svc.cluster.local:9092"
    - name: KAFKA_TOPIC
      value: "game_info"

  volumes:
    - name: kafka-script
      configMap:
        name: kafka-test-script

  driver:
    config:
      volumeMounts:
        - name: kafka-script 
          mountPath: /opt/spark/work-dir
  executor:
    config:
      volumeMounts:
        - name: kafka-script
          mountPath: /opt/spark/work-dir