apiVersion: v1
kind: ConfigMap
metadata:
  name: steam-producer-config
data:
  BOOTSTRAP_SERVERS: "simple-kafka-broker-default-bootstrap.default.svc.cluster.local:9093"
  TOPIC_GAME_INFO: "game_info"
  TOPIC_GAME_COMMENTS: "game_comments"
  FILTERS: "topsellers"
  PAGE_LIST: "1"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: steam-producer
spec:
  backoffLimit: 5            
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: steam-producer
          image: steam-producer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: steam-producer-config
                  key: BOOTSTRAP_SERVERS
            - name: TOPIC_GAME_INFO
              valueFrom:
                configMapKeyRef:
                  name: steam-producer-config
                  key: TOPIC_GAME_INFO
            - name: TOPIC_GAME_COMMENTS
              valueFrom:
                configMapKeyRef:
                  name: steam-producer-config
                  key: TOPIC_GAME_COMMENTS
            - name: FILTERS
              valueFrom:
                configMapKeyRef:
                  name: steam-producer-config
                  key: FILTERS
            - name: PAGE_LIST
              valueFrom:
                configMapKeyRef:
                  name: steam-producer-config
                  key: PAGE_LIST
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
