apiVersion: v1
kind: ConfigMap
metadata:
  name: steam-producer-config
data:
  BOOTSTRAP_SERVERS: "simple-kafka-broker-default-bootstrap.default.svc.cluster.local:9093"
  TOPIC_GAME_INFO: "game_info"
  TOPIC_GAME_COMMENTS: "game_comments"
  TOPIC_PLAYER_COUNT: "player_count"
  FILTERS: "topsellers"
  PAGE_LIST: "1"
  KAFKA_SECURITY_PROTOCOL: "SSL"
  KAFKA_SSL_CA_LOCATION: "/stackable/tls/ca.crt"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: steam-producer
spec:
  backoffLimit: 0 # Fail fast for debugging
  template:
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      restartPolicy: Never
      volumes:
        - name: tls
          ephemeral:
            volumeClaimTemplate:
              metadata:
                annotations:
                  secrets.stackable.tech/class: tls
                  secrets.stackable.tech/scope: pod
              spec:
                storageClassName: secrets.stackable.tech
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: "1"
      containers:
        - name: steam-producer
          image: steam-producer:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: tls
              mountPath: /stackable/tls
          env:
            - name: BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: steam-producer-config
                  key: BOOTSTRAP_SERVERS
            - name: TOPIC_GAME_INFO
              valueFrom:
                configMapKeyRef:
                  name: steam-producer-config
                  key: TOPIC_GAME_INFO
            - name: TOPIC_GAME_COMMENTS
              valueFrom:
                configMapKeyRef:
                  name: steam-producer-config
                  key: TOPIC_GAME_COMMENTS
            - name: FILTERS
              valueFrom:
                configMapKeyRef:
                  name: steam-producer-config
                  key: FILTERS
            - name: PAGE_LIST
              valueFrom:
                configMapKeyRef:
                  name: steam-producer-config
                  key: PAGE_LIST
            - name: KAFKA_SECURITY_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: steam-producer-config
                  key: KAFKA_SECURITY_PROTOCOL
            - name: KAFKA_SSL_CA_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: steam-producer-config
                  key: KAFKA_SSL_CA_LOCATION
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
