---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  image:
    productVersion: 3.9.3
  clusterConfig:
    tls:
      serverSecretClass: null
      quorumSecretClass: null
  servers:
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            memory:
              limit: 512Mi
            cpu:
              max: "0.5"